#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi
if [ -d /etc/VpsPackdir ]
then
echo ""
else
mkdir /etc/VpsPackdir
fi

if [ -d /etc/VpsPackdir/senha ]
then
echo ""
else
mkdir /etc/VpsPackdir/senha
fi

if [ -d /etc/VpsPackdir/limite ]
then
echo ""
else
mkdir /etc/VpsPackdir/limite
fi
if [ "$1" = "" ]; then
clear
echo -e "\033[36;37m PAINEL DE GERENCIAMENTO DA VPS\033[0m"
echo -e "\033[0;35m------------------------------------------------------------\033[0m"
echo -e "\033[1;36m[\033[1;31m1\033[1;36m] - GERÊNCIAR USUÁRIOS\033[01;37m"
echo -e "\033[1;36m[\033[1;31m2\033[1;36m] - BACKUP(\033[01;37m""\033[01;31mFTP\033[01;37m""\033[01;36m)\033[01;37m"
echo -e "\033[1;36m[\033[1;31m3\033[1;36m] - ACESSOS EM TEMPO REAL\033[01;37m"
echo -e "\033[1;36m[\033[1;31m4\033[1;36m] - LIMITAR CONEXÕES (\033[01;37m""\033[01;31mKILL MULTI-LOGIN\033[01;37m""\033[01;36m)\033[01;37m"
echo -e "\033[1;36m[\033[1;31m5\033[1;36m] - MEDIR LINK DE INTERNET\033[01;37m"
echo -e "\033[1;36m[\033[1;31m6\033[1;36m] - GERÊNCIAR SISTEMA\033[01;37m"
echo -e "\033[1;36m[\033[1;31m7\033[1;36m] - MENU ADM\033[01;37m"
echo -e "\033[1;36m[\033[1;31m8\033[1;36m] - MENU OPENVPN\033[01;37m"
echo -e "\033[1;36m[\033[1;31m9\033[1;36m] - MUDAR O COMANDO ADM\033[0m"
echo -e "\033[0;35m------------------------------------------------------------\033[0m"
read -p "RESPOSTA: " op
else
op="$1"
fi
case $op in
1)clear
/usr/local/bin/user
exit
;;
2)clear
/usr/local/bin/backup
exit
;;
3)clear
while true; do
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
echo -e " \033[42;30m   USUARIO                :               CONEXOES   \033[0m"
echo -e "\033[1;37m -------------------------------------------------------\033[0m"
        for usur in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi systemd-[a-z] |grep -vi systemd-[0-9]`; do
	usurnum=$(ps -u $usur |grep sshd |wc -l)
        echo -e "\033[1;33m    $(printf '%-42s%s' $usur $usurnum) \033[0m"
        echo -e "\033[1;37m -------------------------------------------------------\033[0m"
        done
  echo -e "\033[1;31mPARA VOLTAR PRESSIONE ENTER\033[0m"
read -p " "
sleep 1s
  adm
  exit
done
exit
;;
4)clear
/usr/local/bin/limiter
exit
;;
5)clear
/usr/local/bin/teste
exit
;;
6)clear
/usr/local/bin/system
exit
;;
7)clear
/usr/local/bin/adm2
exit
;;
8)
ovpn
exit
;;
9)
if [[ -e /usr/local/bin/antigo ]]; then
antigo > /dev/null
rm -rf /usr/local/bin/antigo > /dev/null
 else
echo " "
clear
fi
echo -e "\033[1;33m"
read -p "Qual o nome do novo comando?: " cmdo
echo -e "\033[0m"
if [[ -e /usr/local/bin/$cmdo ]]; then
echo -e "Comando $cmdo ja Existente"
adm
exit
 else
echo -e "Mudando comando"
fi
touch /usr/local/bin/$cmdo > /dev/null
sleep 1s
echo "#!/bin/bash
echo -e " "
adm
exit" >> /usr/local/bin/$cmdo
echo -e "\033[1;33mO Novo Comando e:\033[1;31m $cmdo \033[1;33mObrigado por usar Adm Manager\033[0m"
sleep 1s
touch /usr/local/bin/antigo
sleep 1s
##
echo "#!/bin/bash
sleep 1s
clear
rm -rf /usr/local/bin/$cmdo" >> /usr/local/bin/antigo
##
 echo -e "\033[1;31mPARA VOLTAR PRESSIONE ENTER\033[0m"
chmod 777 /usr/local/bin/$cmdo
chmod 777 /usr/local/bin/antigo
read -p " "
sleep 1s
adm
  exit
;;
*)
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%44s%s%-20s\n' "OPÇÃO INVÁLIDA..." ; tput sgr0
sleep 1
exit
;;
esac
exit

