#! /bin/bash
clear
echo -e "\033[36;37m PAINEL DE GERENCIAMENTO DA VPS\033[0m"
echo -e "\033[0;35m------------------------------------------------------------\033[0m"
echo
while [  "$op"  !=  "3" ]
do
echo -e '\033[1;36m[\033[1;31m1\033[1;36m] - CRIAR USUÁRIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m2\033[1;36m] - CRIAR USUARIO TEMPORARIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m3\033[1;36m] - DELETAR USUÁRIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m4\033[1;36m] - BLOQUEAR USUÁRIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m5\033[1;36m] - DESBLOQUEAR USUÁRIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m6\033[1;36m] - ALTERAR SENHA DO USUÁRIO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m7\033[1;36m] - ALTERAR LIMITE DE CONEXÃO\033[00;37m'
echo -e '\033[1;36m[\033[1;31m8\033[1;36m] - VER DATA DE VALIDADE DAS CONTAS\033[00;37m'
echo -e '\033[1;36m[\033[1;31m9\033[1;36m] - ALTERAR DATA DE VALIDADE DAS CONTAS\033[00;37m'
echo -e '\033[1;36m[\033[1;31m10\033[1;36m] - NUMERO DE CONTAS CRIADAS ATUALMENTE\033[00;37m'
echo -e '\033[1;36m[\033[1;31m0\033[1;36m] - VOLTAR AO MENU PRINCIPAL\033[00;37m'
echo -e "\033[0;35m------------------------------------------------------------\033[0m"
read -p "RESPOSTA: " op
case $op in
1)clear
echo -e "\033[44;1;37m                         CRIAR USUÁRIO                         \033[0m"
echo
if [ $(id -u) -eq 0 ]; then
    read -p "USUÁRIO: " username
    read -p "SENHA: " password
    read -p "LIMITE DE CONEXÕES: " limiter
    read -p "DIAS DE ATIVIDADE? " dias
    final=$(date "+%Y-%m-%d" -d "+$dias days")
    gui=$(date "+%d/%m/%Y" -d "+$dias days")
    egrep "^$username" /etc/passwd >/dev/null
    if [ $? -eq 0 ]; then
echo	
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "O usuario $username ja existe!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
        exit 1
    else
        pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
        useradd -e $final -M -s /bin/false -p $pass $username
echo
echo
clear
tput setaf 7 ; tput setab 4 ; tput bold ; echo "";
       [ $? -eq 0 ] &&  echo "Usuario $username criado com sucesso! Conta ira expirar dia $gui"  || echo "Nao foi possivel criar o usuario"
tput sgr0
echo "$username $limiter" >> usuarios.db
echo "$limiter" > /etc/VpsPackdir/limite/$username
echo "$password" > /etc/VpsPackdir/senha/$username
sleep 3
clear
/usr/local/bin/user
        fi
    else
    tput setaf 7 ; tput setab 1 ; tput bold ; echo "Este script devera ser executado atraves do usuario root" ; tput sgr0
	sleep 3
	clear
	/usr/local/bin/user
    exit 2
fi
echo "  "
echo "  "
echo "  "
sleep 3
clear
/usr/local/bin/user
exit
;;
2)
  clear 
echo -e "\033[1;32m------------------------------------------------------------\033[0m"
echo -e "\033[1;31m   CRIADOR DE USUARIOS TEMPORARIOS...\033[1;33m
ESSES SAO OS USUARIOS  JA CADASTRADOS NO SEU SISTEMA!\033[0m"
echo -e "\033[1;32m------------------------------------------------------------\033[0m"
for users in `awk -F : '$3 > 900 { print $1 }' /etc/passwd |grep -v "nobody" |grep -vi polkitd |grep -vi system-`
do
echo -e "\033[1;31m                        $users\033[0m"
done
echo -e "\033[1;32m------------------------------------------------------------\033[0m"
/usr/local/bin/usrtemp
/usr/local/bin/user
;;
3)clear
echo -e "\033[44;1;37m                        DELETAR USUÁRIO                        \033[0m"
echo
read -p "NOME DO USUÁRIO QUE DESEJA REMOVER: " user
if [[ -z $user ]]
then
echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou um nome de usuário vazio ou inválido!"; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit 1
else
    if [[ `grep -c /$user: /etc/passwd` -ne 0 ]]
    then
        ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
        if [[ `grep -c $user /tmp/rem` -eq 0 ]]
        then
		echo
        deluser $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo ""; echo "O usuário $user foi removido com sucesso!" ; tput sgr0
            grep -v ^$user[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
sleep 3
clear
/usr/local/bin/user
            exit 1
        else
		echo
tput setaf 7 ; tput setab 1 ; tput bold ;  echo "Usuário conectado. Desconectando..."  ; tput sgr0
            pkill -f "$user"
            deluser $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo "";  echo "O usuário $user foi removido com sucesso!" ; tput sgr0
            grep -v ^$user[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
sleep 3
clear
/usr/local/bin/user
            exit 1
        fi
    else
tput setaf 7 ; tput setab 1 ; tput bold ; echo "O usuário $user não existe!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit
    fi
fi
;;
4)clear
echo -e "\033[44;1;37m                       BLOQUEAR USUÁRIO                        \033[0m"
echo
read -p "NOME DO USUÁRIO QUE DESEJA BLOQUEAR: " user
if [[ -z $user ]]
then
echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou um nome de usuário vazio ou inválido!"; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit 1
else
    if [[ `grep -c /$user: /etc/passwd` -ne 0 ]]
    then
        ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
        if [[ `grep -c $user /tmp/rem` -eq 0 ]]
        then
		echo
        passwd -l $user > /dev/null
        usermod -L $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo ""; echo "O usuário $user foi bloqueado com sucesso!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
        exit 1
        else
		echo
tput setaf 7 ; tput setab 1 ; tput bold ;  echo "Usuário conectado. Desconectando..."  ; tput sgr0
            pkill -f "$user"
            passwd -l $user > /dev/null
            usermod -L $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo "";  echo "O usuário $user foi bloqueado com sucesso!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
            exit 1
        fi
    else
	echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "O usuário $user não existe!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit
    fi
fi

;;
5)clear
echo -e "\033[44;1;37m                     DESBLOQUEAR USUÁRIO                       \033[0m"
echo
read -p "NOME DO USUÁRIO QUE DESEJA DESBLOQUEARBLOQUEAR: " user
if [[ -z $user ]]
then
echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou um nome de usuário vazio ou inválido!"; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit 1
else
    if [[ `grep -c /$user: /etc/passwd` -ne 0 ]]
    then
	    echo
        ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
        if [[ `grep -c $user /tmp/rem` -eq 0 ]]
        then
            passwd -u $user > /dev/null
            usermod -U $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo ""; echo "O usuário $user foi desbloqueado com sucesso!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
            exit 1
        else
		echo
tput setaf 7 ; tput setab 1 ; tput bold ;  echo "Usuário conectado. Desconectando..."  ; tput sgr0
            pkill -f "$user"
            passwd -u $user > /dev/null
            usermod -U $user > /dev/null
tput setaf 7 ; tput setab 4 ; tput bold ; echo "";  echo "O usuário $user foi desbloqueado com sucesso!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
            exit 1
        fi
    else
	echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "O usuário $user não existe!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit
    fi
fi

;;
6)clear
echo -e "\033[44;1;37m                  ALTERAR SENHA DO USUÁRIO                     \033[0m"
echo
read -p "NOME DO USUÁRIO PARA ALTERARAÇÃO DA SENHA: " user
if [[ -z $user ]]
then
echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou um nome de usuário vazio ou inválido!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
    exit 1
else
    if [[ `grep -c /$user: /etc/passwd` -ne 0 ]]
    then
	    echo
        read -p "Digite uma nova senha para o usuário: " password
        sizepass=$(echo ${#password})
        if [[ $sizepass -lt 6 ]]
        then
		echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "A senha não foi alterada!" ; echo "Você digitou uma senha muito curta!" ; echo "Para manter o usuário seguro use no mínimo 6 caracteres" ; echo "combinando diferentes letras e números." ; tput sgr0
sleep 3
echo "$password" > /etc/VpsPackdir/senha/$user
clear
/usr/local/bin/user
            exit 1
            else
            ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
            if [[ `grep -c $user /tmp/rem` -eq 0 ]]
            then
			echo
            echo "$user:$password" | chpasswd
tput setaf 7 ; tput setab 4 ; tput bold ; echo "A senha do usuário $user foi alterada para: $password" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
            exit 1
            else
            echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Usuário conectado. Desconectando..." ; tput sgr0
                pkill -f $user
                echo "$user:$password" | chpasswd
tput setaf 7 ; tput setab 4 ; tput bold ; echo "A senha do usuário $user foi alterada para: $password" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
            exit 1
            fi
            fi
            else
			echo
tput setaf 7 ; tput setab 1 ; tput bold ; echo "O usuário $user não existe!" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
    fi
fi
/usr/local/bin/user
exit
;;
7)clear
echo -e "\033[44;1;37m                 ALTERAR LIMITE DE CONEXÃO                     \033[0m"
echo
database="/root/usuarios.db"
if [ ! -f "$database" ]
then
    tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "Arquivo $database não encontrado" ; echo "" ; tput sgr0
sleep 3
clear
/usr/local/bin/user
exit 1
else
	tput setaf 2 ; tput bold ; echo ""; echo "Limite de conexões simultâneas dos usuários:" ; tput sgr0
    tput setaf 3 ; tput bold ; echo "" ; cat $database ; echo "" ; tput sgr0
    read -p "Nome de usuário para alterar o limite: " usuario
    if [[ -z $usuario ]]
    then
        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Você digitou um nome de usuário vazio ou não existente na lista!" ; echo "" ; tput sgr0
        sleep 3
clear
/usr/local/bin/user
        exit 1
    else
        if [[ `grep -c "^$usuario " $database` -gt 0 ]]
        then
            read -p "Número de conexões simultâneas permitidas para o usuário: " sshnum
            if [[ -z $sshnum ]]
            then
                tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Você digitou um número inválido!" ; echo "" ; tput sgr0
            sleep 3
clear
/usr/local/bin/user
            exit 1
            else
                if (echo $sshnum | egrep [^0-9] &> /dev/null)
                then
                    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Você digitou um número inválido!" ; echo "" ; tput sgr0
                     sleep 3
clear
/usr/local/bin/user
                    exit 1
                else
                    if [[ $sshnum -lt 1 ]]
                    then
                        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Você deve digitar um número de conexões simultâneas maior que zero!" ; echo "" ; tput sgr0

sleep 3
clear
/usr/local/bin/user
                        exit 1
                    else
                        grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/a
                        sleep 1
                        mv /tmp/a /root/usuarios.db
                        echo $usuario $sshnum >> /root/usuarios.db
                        tput setaf 7 ; tput setab 4 ; tput bold ; echo "" ; echo "O número de conexões simultâneas permitidas para o usuário $usuario foi alterado!" ; tput sgr0
                        sleep 3
echo "$limiter" > /etc/VpsPackdir/limite/$usuario
clear
/usr/local/bin/user
                        exit
                    fi
                fi
            fi
        else
            tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "O usuário $usuario não foi encontrado na lista!" ; echo "" ; tput sgr0
            sleep 3
clear
/usr/local/bin/user
            exit 1
        fi
    fi
fi
/usr/local/bin/user
exit
;;
8)clear
echo -e "\033[44;1;37m                    VALIDADE DAS CONTAS                        \033[0m"
echo
echo -e  '\033[01;34m  USUÁRIOS                      VALIDADE: \033[01;37m'

echo '--------------------------------------------------------------------'
touch /tmp/ussh
cat /etc/passwd |grep -v ovpn > /tmp/ussh

awk -F : '$3 >= 500 { print $1 }' /tmp/ussh | grep -v '^nobody' | while read user

  do

    expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"

    if [[ $expire == "never" ]]

    then

        nunca="Nunca"

        printf '  %-30s%s\n' "$user" "Nunca"

    else

        databr="$(date -d "$expire" +"%Y%m%d")"

        hoje="$(date -d today +"%Y%m%d")"

        if [ $hoje -ge $databr ]

        then

            datanormal="$(date -d"$expire" '+%d/%m/%Y')"

            printf '  %-30s%s' "$user" "$datanormal       " ;tput setaf 7 ; tput setab 1 ; tput bold ; echo "(EXPIRADO)" ; tput sgr0

            echo "exp" > /tmp/exp

        else

            datanormal="$(date -d"$expire" '+%d/%m/%Y')"

            printf '  %-30s%s\n' "$user" "$datanormal"

        fi

    fi
echo '--------------------------------------------------------------------'
  done
rm -rf /tmp/ussh
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%48s%s%-20s\n' "" ; tput sgr0

echo
echo
echo

echo -e '\033[01;33mTecle ENTER para voltar ao menu de administração...\033[01;37m'

read ok

echo $ok

/usr/local/bin/user
exit
;;
9)clear
echo -e "\033[44;1;37m                 MUDAR DATA DE EXPIRAÇÃO                       \033[0m"
echo
touch /tmp/ussh
cat /etc/passwd |grep -v ovpn > /tmp/ussh
echo "Lista de usuários e datas de expiração:"
awk -F : '$3 >= 500 { print $1 }' /tmp/ussh | grep -v '^nobody' | while read user
  do
    expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"
    if [[ $expire == "never" ]]
    then
        nunca="Nunca"
        printf '  %-30s%s\n' "$user" "Nunca"
    else
        databr="$(date -d "$expire" +"%Y%m%d")"
        hoje="$(date -d today +"%Y%m%d")"
        if [ $hoje -ge $databr ]
        then
            datanormal="$(date -d"$expire" '+%d/%m/%Y')"
            printf '  %-30s%s' "$user" "$datanormal" ; echo "expirado"
            echo "exp" > /tmp/exp
        else
            datanormal="$(date -d"$expire" '+%d/%m/%Y')"
            printf '  %-30s%s\n' "$user" "$datanormal"
        fi
    fi
  done
rm -rf /tmp/ussh
tput sgr0
echo ""
read -p "Nome do usuário para alterar a data de expiração: " usuario
if [[ -z $usuario ]]
then
    echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou um nome de usuário vazio ou inválido!" ; tput sgr0
    echo ""
   echo " "
sleep 3
clear
/usr/local/bin/user
exit 1
else
    if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
    then
        read -p "Digite uma nova data de expiração (DIA/MÊS/ANO): " inputdate
        sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
        if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
        then
            if [[ -z $inputdate ]]
            then
                echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2018" ; tput sgr0
                echo ""
                echo " "
sleep 3
clear
/usr/local/bin/user
                exit 1
            else
                if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
                then
                    today="$(date -d today +"%Y%m%d")"
                    timemachine="$(date -d "$sysdate" +"%Y%m%d")"
                    if [ $today -ge $timemachine ]
                    then
                        echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou uma data passada ou o dia atual!" ; echo "Digite uma data futura e válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2018" ; tput sgr0
                        echo ""
                       echo " "
sleep 3
clear
/usr/local/bin/user
                        exit 1
                    else
                        chage -E $sysdate $usuario
                        echo ""
tput setaf 7 ; tput setab 4 ; tput bold ; echo "A data de expiração do usuário $usuario foi alterada para: $inputdate" ; tput sgr0
                        echo ""
                        echo " "
sleep 3
clear
/usr/local/bin/user
                        exit 1
                    fi
                else
                    echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2018" ; tput sgr0
                    echo ""
                   echo " "
sleep 3
clear
/usr/local/bin/user
exit 1
                fi
            fi
        else
            echo ""
tput setaf 7 ; tput setab 1 ; tput bold ; echo "Você digitou uma data inválida ou inexistente!" ; echo "Digite uma data válida no formato DIA/MÊS/ANO" ; echo "Por exemplo: 21/04/2018" ; tput sgr0
            echo
            echo
sleep 3
clear
/usr/local/bin/user
exit 1
        fi
    else
        echo " "
tput setaf 7 ; tput setab 1 ; tput bold ; echo "O usuário $usuario não existe!" ; tput sgr0
        echo " "
        echo " "
sleep 3
clear
/usr/local/bin/user
exit 1
    fi
fi
/usr/local/bin/user
exit
;;
10)clear
echo -e "\033[44;1;37m                NUMERO DE CONTAS CRIADAS                       \033[0m"
CONTAS=`cat usuarios.db | wc -l`
echo
echo -e '\033[01;32mAtualmente no seu servidor o numero de contas criadas é:\033[00;37m' $CONTAS
echo
echo 'Para voltar ao menu de administração tecle ENTER...'
read ok
/usr/local/bin/user
exit
;;
0)clear
/usr/local/bin/h
exit
;;
*)
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%48s%s%-20s\n' "OPÇÃO INVÁLIDA..." ; tput sgr0
sleep 1
exit
;;
esac
read
done

