#!/bin/bash

echo -e "\033[41;1;37mOPÇOES DE REMOÇAO DE USUARIOS:\033[0m"
echo -e "\033[1;36mQual Nome Do Usuario?\033[0m"
read -p " " name

if cat /etc/passwd |grep $name: > /dev/null
 then
 echo " "
 else
 echo "USUARIO $name NAO EXISTE"
 sleep 5s
 exit
 fi
if [[ -z $name ]]
then
echo "VAZIO"
sleep 5s
exit
fi

sleep 1s
echo -e "\033[1;36m
1) Deletar usuario $name
2) Deletar e Desconectar usuario $name\033[0m"
read -p "opção: " option

if [[ -z $option ]]
then
echo "OPCAO INVALIDA"
sleep 5s
clear
exit
fi

 if [ $option -eq 1 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 echo "..."
 sleep 1s
echo -e "\033[41;1;37mREMOVIDO \033[0m"
 exit
 fi

 if [ $option -eq 2 ]; then
 userdel --force $name > /dev/null 2>/dev/null
 kill -9 `ps aux |grep -vi '[a-z]$name' |grep -vi '$name[a-z]' |grep -v '[1-9]$name' |grep -v '$name[1-9]' |grep $name |awk {'print $2'}` 2> /dev/null
 echo "..."
 sleep 1s 
echo -e "\033[41;1;37mREMOVIDO \033[0m"
 exit
 fi
case $option in
 *)
echo -e "essa opçao não existe\033[0m"
sleep 1s
exit
;;
esac

