#!/bin/bash
if [ ! "$BASH" ]
then
echo "Este script foi feito para funcionar com o bash
Reiniciando o Script usando BASH em 3 segundos..."
sleep 3
bash $0 $@
exit $?
fi

menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"
##
eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Ethernet" | awk '{print $1}')
##
#identificacao automatica do ip
AIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
if [[ "$AIP" = "" ]]; then
		AIP=$(wget -4qO- "http://whatismyip.akamai.com/")
fi
##VERIFICACAO DAS PORTAS##
variaveldaport=$(cat /etc/default/dropbear |egrep -o "80" |wc -l)
if [ "$variaveldaport" = "0" ]; then
spt="80"
else
spt="280"
fi
variaveldaport2=$(cat /etc/default/dropbear |egrep -o "8080" |wc -l)
if [ "$variaveldaport2" = "0" ]; then
spt2="8080"
else
spt2="488"
fi
variaveldaport3=$(cat /etc/default/dropbear |egrep -o "8799" |wc -l)
if [ "$variaveldaport3" = "0" ]; then
spt3="8799"
else
spt3="777"
fi
variaveldaport4=$(cat /etc/default/dropbear |egrep -o "3128" |wc -l)
if [ "$variaveldaport4" = "0" ]; then
spt4="3128"
else
spt4="8000"
fi
touch /tmp/portas
echo "22" >> /tmp/portas
touch /tmp/portas2
echo "$spt" >> /tmp/portas2
echo "$spt2" >> /tmp/portas2
echo "$spt3" >> /tmp/portas2
echo "$spt4" >> /tmp/portas2

####FIMDAIDENTIFICACAODEPORTA80#####
echo -e "$cyanClaro
INSTALADOR DO PROXY SQUID
$fim"
read -p "ENTER PARA PROSSEGUIR"
read -p "Digite seu IP: " -e -i $AIP ip
echo -e "$cyanClaro
Instalando SQUID3...$fim"
apt-get update 1>/dev/null 2>/dev/null
apt-get upgrade -y 1>/dev/null 2>/dev/null
apt-get install squid3 -y 1>/dev/null 2>/dev/null
echo -e "$azulClaro
INICIANDO INSTALAÇAO...$fim"
sleep 3s
echo -e "\033[0m"
echo -e "\033[1;33mDESEJA CONFIGURAR O SQUID PARA UM FUNCIONAMENTO MAIS GENERICO? OU MAIS SEGURO?

\033[1;31mO FUNCIONAMENTO GENERICO PERMITE QUE VOCE ADICIONE UM DOMINIO COMO PAYLOAD E EVENTUALMENTE USE TAMBEM OS SEUS SUBDOMINIOS, INDISPENSAVEL PARA TESTES EM DOMINIOS DAS OPERADORAS, POREM SEU SQUID PODE SER USADO COMO PROXY PUBLICO COM DNS REVERSO!

O FUNCIONAMENTO SEGURO GARANTE MAIOR PROTECAO, POREM VOCE IRA TER QUE ADICIONAR O DOMINIO DO HOST DA PAYLOAD EXATAMENTE COMO USA... EX: \033[1;36mwww.host.com/sub/sub1/oarqo.php\033[1;31m PARA O CORRETO FUNCIONAMENTO

QUAL SQUID VAI QUERER?
[1] - GENERICO
[2] - SEGURO"
read -p "opção: " squidinstall
echo -e "\033[0m"
sleep 1s
echo -e "\033[1;33mINSTALACAO PADRAO OU PERSONALIZADA?"
read -p "[1] - PADRAO
[2] - PERSONALIZADA
: " padr
echo -e "\033[0m"
case $padr in
1)
insta="1"
;;
2)
insta="2"
;;
*)
insta="1"
;;
esac
cp /etc/ssh/sshd_config /etc/ssh/squidbak
echo -e " " >> /etc/ssh/sshd_config
touch /tmp/portas2
echo -e "$spt\n8080\n8799\n3128" >> /tmp/portas2
##DTCsquid
if [[ -e /etc/squid/squid.conf ]]; then
opt="2"
sleep 2s
else
 if [[ -e /etc/squid3/squid.conf ]]; then
opt="1"
sleep 2s
else
echo -e "\033[1;36mQUAL SISTEMA ESTA USANDO?
[1] DEBIAN
[2] UBUNTO"
read -p "opção: " opt
  fi
fi
###
case $squidinstall in
  2)
#Squid Seguro
sleep 2s
###PAYLOADS###
touch /etc/payloads
echo -e "bookclaro.com.br
clarocurtas.com.br
claroideias.com.br
claromusica.com
clarosomdechamada.com.br
portalrecarga.vivo.com.br
vivo.ddivulga.com" > /etc/payloads
###FIMPAYLOADS###

##SYS###DEBIAN
if [ $opt -eq 1 ]; then
echo "#ConfiguracaoSquiD
acl url1 dstdomain -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $ip
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port $spt
http_port $spt2
http_port $spt3
http_port $spt4

visible_hostname PROXYSERVER

forwarded_for off
pipeline_prefetch on
" > /etc/squid3/squid.conf
##
##
echo -e "$azulClaro
CONFIGURANDO...$fim"
echo -e "$cyanClaro REINICIANDO SERVIÇOS...$fim"
squid3 -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid3 restart 1>/dev/null 2>/dev/null
sleep 1s
fi

##SYS###UBUNTU
if [ $opt -eq 2 ]; then
echo "#ConfiguracaoSquiD
acl url1 dstdomain -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $ip
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port $spt
http_port $spt2
http_port $spt3
http_port $spt4

visible_hostname PROXYSERVER

forwarded_for off
pipeline_prefetch on
" > /etc/squid/squid.conf
##
##
echo -e "$azulClaro
CONFIGURANDO...$fim"
echo -e "$cyanClaro REINICIANDO SERVIÇOS...$fim"
squid -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid restart 1>/dev/null 2>/dev/null
sleep 1s
fi

sleep 1s
#### ethool ##### 3 parte ######
if [ "$insta" = "2" ]; then
echo -e "\033[1;36mAPLICAR SISTEMA PARA MELHORAR PACOTES SSH?
[s/n]\033[0m"
read -p ": " ssh
 if [ "$ssh" = "s" ]
then
echo -e "$verde Correção de problemas de pacotes no SSH...$fim"
apt-get install ethtool -y 1>/dev/null 2>/dev/null
read -p "Digite o nome da sua interface de rede PADRAO: $eth" interface
   if [ "$interface" = "" ]
then
interface=eth0
   fi
ethtool -G $interface rx 999999999 tx 999999999 1>/dev/null 2>/dev/null
echo -e "\033[1;36m
OPEN SSH RODANDO NAS PORTAS:"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "$fim"
echo -e "\033[1;36m
PROXY SQUID RODANDO NAS PORTAS"
cat /tmp/portas2
rm -rf /tmp/portas2
echo -e "$fim"
sleep 5s
exit
 fi
fi
echo -e "\033[1;36m
OPEN SSH RODANDO NAS PORTAS:"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "$fim"
echo -e "\033[1;36m
PROXY SQUID RODANDO NAS PORTAS"
cat /tmp/portas2
rm -rf /tmp/portas2
echo -e "$fim"
sleep 5s
exit
;;
  1)
### Squid Generico
sleep 2s
###PAYLOADS###
touch /etc/payloads
echo -e ".bookclaro.com.br
.claro.com.ar
.claro.com.br
.claro.com.co
.claro.com.ec
.claro.com.gt
.claro.com.ni
.claro.com.pe
.claro.com.sv
.claro.cr
.clarocurtas.com.br
.claroideas.com
.claroideias.com.br
.claromusica.com
.clarosomdechamada.com.br
.clarovideo.com
.facebook.net
.facebook.com
.netclaro.com.br
.oi.com.br
.oimusica.com.br
.speedtest.net
.tim.com.br
.timanamaria.com.br
.vivo.com.br
.rdio.com
.compute-1.amazonaws.com
.portalrecarga.vivo.com.br
.vivo.ddivulga.com" > /etc/payloads
###FIMPAYLOADS###

##SYS###DEBIAN
if [ $opt -eq 1 ]; then
echo "#ConfiguracaoSquiD
acl url1 url_regex -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $ip
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port $spt
http_port $spt2
http_port $spt3
http_port $spt4

visible_hostname PROXYSERVER

forwarded_for off
pipeline_prefetch on
" > /etc/squid3/squid.conf
##
##
echo -e "$azulClaro
CONFIGURANDO...$fim"
echo -e "$cyanClaro REINICIANDO SERVIÇOS...$fim"
squid3 -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid3 restart 1>/dev/null 2>/dev/null
sleep 1s
fi

##SYS###UBUNTU
if [ $opt -eq 2 ]; then
echo "#ConfiguracaoSquiD
acl url1 url_regex -i '/etc/payloads'
acl url2 dstdomain -i 127.0.0.1
acl url3 dstdomain -i localhost
acl url4 dstdomain -i $ip
always_direct allow all

http_access allow url1
http_access allow url2
http_access allow url3
http_access allow url4
http_access deny all
header_access From deny all
header_access Via deny all
header_access Server deny all

#portas
http_port $spt
http_port $spt2
http_port $spt3
http_port $spt4

visible_hostname PROXYSERVER

forwarded_for off
pipeline_prefetch on
" > /etc/squid/squid.conf
sleep 1s
##
##
echo -e "$azulClaro
CONFIGURANDO...$fim"
echo -e "$cyanClaro REINICIANDO SERVIÇOS...$fim"
squid -k reconfigure 1>/dev/null 2>/dev/null
service ssh restart 1>/dev/null 2>/dev/null
service squid restart 1>/dev/null 2>/dev/null
sleep 1s
fi
sleep 1s
#### ethool ##### 3 parte ######
if [ "$insta" = "2" ]; then
echo -e "\033[1;36mAPLICAR SISTEMA PARA MELHORAR PACOTES SSH?
[s/n]\033[0m"
read -p ": " ssh
 if [ "$ssh" = "s" ]
then
echo -e "$verde Correção de problemas de pacotes no SSH...$fim"
apt-get install ethtool -y 1>/dev/null 2>/dev/null
read -p "Digite o nome da sua interface de rede PADRAO: $eth" interface
   if [ "$interface" = "" ]
then
interface=eth0
   fi
ethtool -G $interface rx 999999999 tx 999999999 1>/dev/null 2>/dev/null
echo -e "\033[1;36m
OPEN SSH RODANDO NAS PORTAS:"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "$fim"
echo -e "\033[1;36m
PROXY SQUID RODANDO NAS PORTAS"
cat /tmp/portas2
rm -rf /tmp/portas2
echo -e "$fim"
sleep 5s
exit
 fi
fi
echo -e "\033[1;36m
OPEN SSH RODANDO NAS PORTAS:"
cat /tmp/portas
rm -rf /tmp/portas
echo -e "$fim"
echo -e "\033[1;36m
PROXY SQUID RODANDO NAS PORTAS"
cat /tmp/portas2
rm -rf /tmp/portas2
echo -e "$fim"
sleep 5s
exit
;;
  *)
rm -rf /tmp/portas
rm -rf /tmp/portas2
exit
;;
esac
exit
